---
version: "3"

services:
   flask-app:
      build:
         context: ./
         dockerfile: ./Dockerfile
      ports:
         - 5000:5000
      image: avlavelle/midterm_iss

      volumes:

         - ./config.yaml:/config.yaml
                        
